name: smivox_inventory_software
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/onboarding/
     - assets/fonts/
     - assets/logo/
     - assets/images/
     - assets/svgs/
     - assets/drawer/
     - assets/home/
     - assets/pos/
     - assets/inventory/
     - .env
     - assets/data/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Light.ttf
#           weight: 400
         - asset: assets/fonts/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Poppins-Bold.ttf

